# Generated by Django 2.1.1 on 2018-09-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articalHeadline', models.TextField()),
                ('articalBody', models.CharField(max_length=200)),
            ],
        ),
    ]
